import { Manrope } from "next/font/google";
import "./globals.css";
import HeroPage from "./Hero/Page";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ['200' , '300', '400' , '500', '600' , '700' , '800'],
  display: 'swap'
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable}`}
      >
        <HeroPage/>
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
